site_name: Outset Docs
nav:
  - Home: README.md
  - Demo: demo.md
  - Parts:
    - Battery: battery.md
    - Keypad: keypad.md
    - Pinout: pinout.md
    - Radio: radio.md
    - Real Time Clock: rtc.md
    - Screen: screen.md
    - Trackpad: trackpad.md
  - Diagrams:
    - Block Diagram: blockDiagram.md
    - Schematics: schematic.md
markdown_extensions:
  - admonition
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
watch:
 - docs